### ISSUE TITLE
Separate core from Confluent stuff

### ISSUE THREAD

**Issue by NeQuissimus** [embeddedkafka/embedded-kafka#1]
Let's make two separate modules, one for the Open Source Kafka things, one for the Confluent-related additions.

**Comment by NeQuissimus** [comment]
I guess it's not really clear what I meant :)

I was wondering whether it would make sense to separate into two repos and thereby have independent release pushes.

We could thereby align the core release versions with Kafka versions and the Confluent module with the Confluent Platform version numbers.

Right now, for example, I would like to update to Kafka 2.1.0 but because the corresponding Confluent Platform has not been published, we have to wait with the entire library.

**Comment by francescopellegrini** [comment]
Having a separate release cycle would be nice for sure: I'm wondering how we can keep the sub-project git history though..

**Comment by abazylewicz** [comment]
You can split subfolder to separate repo with git filter-branch https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/
It is constrained to one branch/one folder afaik.

**Comment by francescopellegrini** [comment]
Oh yeah, you're right, I used that command a long ago for the same purpose.

I'll give it a try as soon as #11 will be merged.

**Comment by francescopellegrini** [comment]
Would you like me to create a new repo named `embedded-kafka-schema-registry` (as I proposed in #7) under this org and push there the code?

**Comment by francescopellegrini** [comment]
Embedded Schema Registry tests are currently relying on some test classes of the `embedded-kafka` sub-module, like `EmbeddedKafkaSpecSupport`: would you prefer me to clone these classes into the new project or do you think it would be a good idea to publish the `test` artifacts too?

**Comment by NeQuissimus** [comment]
I think it should be fine to just clone them. I don't anticipate too much of a mess from this :)

And I do like the name and version changes. That is exactly what I had in mind originally.

**Comment by francescopellegrini** [comment]
Ok, thank you! I'll push to the new repo as soon as #13 is merged, then I'll also rework #9.

I managed to compile the new Schema Registry project by locally publishing this project, but Travis won't be able to until we publish at least a snapshot of it.

**Comment by NeQuissimus** [comment]
Thanks for all the work and sorry I can't help too much, been way too busy recently...

**Comment by francescopellegrini** [comment]
I pushed embeddedkafka/embedded-kafka-schema-registry#1

**Comment by francescopellegrini** [comment]
I pushed again to #10 removing the `schema-registry` sub-module.

**Comment by francescopellegrini** [comment]
Schema Registry code has been pushed to [the new repo](https://github.com/embeddedkafka/embedded-kafka-schema-registry).

**Comment by francescopellegrini** [comment]
Fixed in #10.
