### ISSUE TITLE
Embedded Kafka Message From Previous Test Exists In New Test

### ISSUE THREAD

**Issue by no-stupid-questions** [embeddedkafka/embedded-kafka#103]
Im using embeddedkafka 2.1.1 with sbt 1.3.0 and scala 2.11.12.
I have a test that should be ignored 
```

\"publish corresponding message to Kafka\" in {

      val uri = new URI(\"http\", \"localhost:9000", "/v1/data/datasets/", """datasetIds=["dataset1","dataset2"]""", null)

      val aRequest = play.api.test.FakeRequest(method = "DELETE", uri = uri.toASCIIString, headers = play.api.test.FakeHeaders(), body = AnyContentAsEmpty)

      when(mockMDSRepo.deleteMetaDatasets(Set("dataset1", "dataset2"))) thenReturn DeleteSuccess

      implicit val config: EmbeddedKafkaConfig = EmbeddedKafkaConfig(kafkaPort = 9092, zooKeeperPort = 2181)
      runningwithkafka
        val kafkaPublisher = new KafkaPublisherImpl
        val dsController = new MetaDatasetController(mockMDSRepo, mockSchemaRepo, mockJobRepo, mockAppRepo, kafkaPublisher) {
          override def controllerComponents: ControllerComponents = Helpers.stubControllerComponents()
        }
        val results = dsController.deleteDatasets().apply(aRequest)
        status(results) mustBe 204
        contentType(results) mustBe None
        consumeFirstStringMessageFrom(bpa.kafkaTopic) mustBe KafkaMessages.datasetDeletedMessage1
        consumeFirstStringMessageFrom(bpa.kafkaTopic) mustBe KafkaMessages.datasetDeletedMessage2
      EmbeddedKafka.stop()
    }
```

How ever in a later test 
```
 "publish proper dataset created message" in {
      when(mockAppRepo.getAllBPAApplications) thenReturn Set(bpa)
      implicit val config: EmbeddedKafkaConfig = EmbeddedKafkaConfig(kafkaPort = 9092, zooKeeperPort = 2181)
      withRunningKafka {
        val kafkaPublisher = new KafkaPublisherImpl
        val kafkaUtil = new KafkaUtil(kafkaPublisher, mockAppRepo)
        kafkaUtil.publisDatasetCreatedMessage(testMetadataset)
        consumeFirstStringMessageFrom(bpa.kafkaTopic) mustBe KafkaMessages.datasetCreatedMessage1
      }
    }
```
the test fails as the   consumeFirstStringMessageFrom(bpa.kafkaTopic) results in the KafkaMessages.datasetDeletedMessage1 (from ignored test) instead of the testMetadataset that was supposed to be put into kafka

I tried the test classes with BeforeAndAfterEach and BeforeEach starting Embedded kafka and AfterEach stopping Embedded kafka, but i would still get the test failing.

**Comment by francescopellegrini** [comment]
Hi @no-stupid-questions, what do you mean by "should be ignored"? Are you referring to the `ignore` method of ScalaTest? Because it's not present in the code you posted...
On a side note, you should either use `withRunningKafka` closure or the start-stop methods of `EmbeddedKafka` object, not both (and definitely not `stop` inside the closure).

**Comment by no-stupid-questions** [comment]
Hey @francescopellegrini I was a bit scatter brained when I posted that. I guess those code examples were in the middle of me changing from withrunningkafka to embedded start stop the actual code is:

```
"publish corresponding message to Kafka" ignore {

      val uri = new URI("http", "localhost:9000", "/v1/data/datasets/", """datasetIds=["dataset1","dataset2"]""", null)

      val aRequest = play.api.test.FakeRequest(method = "DELETE", uri = uri.toASCIIString, headers = play.api.test.FakeHeaders(), body = AnyContentAsEmpty)

      when(mockMDSRepo.deleteMetaDatasets(Set("dataset1", "dataset2"))) thenReturn DeleteSuccess

      implicit val config: EmbeddedKafkaConfig = EmbeddedKafkaConfig(kafkaPort = 9092, zooKeeperPort = 2181)
      runningwithkafka {
        val kafkaPublisher = new KafkaPublisherImpl
        val dsController = new MetaDatasetController(mockMDSRepo, mockSchemaRepo, mockJobRepo, mockAppRepo, kafkaPublisher) {
          override def controllerComponents: ControllerComponents = Helpers.stubControllerComponents()
        }
        val results = dsController.deleteDatasets().apply(aRequest)
        status(results) mustBe 204
        contentType(results) mustBe None
        consumeFirstStringMessageFrom(bpa.kafkaTopic) mustBe KafkaMessages.datasetDeletedMessage1
        consumeFirstStringMessageFrom(bpa.kafkaTopic) mustBe KafkaMessages.datasetDeletedMessage2
      }
}
```

**Comment by francescopellegrini** [comment]
According to [Scalatest docs](http://doc.scalatest.org/3.1.0/org/scalatest/wordspec/AnyWordSpec.html), ignored tests are not executed, so I really don't see how the code you posted could be influencing later test scenarios..

**Comment by no-stupid-questions** [comment]
Yeah I also don't see how the code I posted could be influencing later test scenarios. That's what's tripping me up, the first test shouldn't even run and but somehow KafkaMessages.datasetDeletedMessage2 (from the "ignored" test) ends up getting returned when consumeFirstStringMessageFrom(bpa.kafkaTopic) is called in the not ignored test.

**Comment by francescopellegrini** [comment]
Are your test scenarios running concurrently, maybe? Here we use the following settings:

```scala
parallelExecution in ThisBuild := false
parallelExecution in Test := false
```

**Comment by no-stupid-questions** [comment]
I seem to have `parallelExecution in Test := false` but not `parallelExecution in ThisBuild := false` , I'll try out both together, thanks for the direction!

**Comment by francescopellegrini** [comment]
Hi @no-stupid-questions, did you manage to solve the issue?

**Comment by no-stupid-questions** [comment]
I havent been able to solve this, but it's okay.
I'll close this issue and the thanks again for the help :+1:
