### ISSUE TITLE
Please provide a way to create multiple brokers

### ISSUE THREAD

**Issue by michkhol** [embeddedkafka/embedded-kafka#164]
In the previous version 2.4.0 there was a way of creating multiple brokers by doing explicit calls to `startZookeeper(port, dir)` and `startKafka(conf, dir)`. Now it seems to be well hidden. Could you bring this possibility back somehow? 
Thanks!

**Comment by francescopellegrini** [comment]
Hi @michkhol,
#163 restricted the access to a method which wasn't really meant to be publicly used.
You can start multiple ZooKeeper nodes and Kafka brokers using the `startZooKeeper` and `startKafka` methods in the `EmbeddedKafka` companion object, which both require an implicit `EmbeddedKafkaConfig`.

**Comment by michkhol** [comment]
Thanks!
