### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by NeQuissimus** [embeddedkafka/embedded-kafka#2]
Use `sbt-ci-release` (https://github.com/olafurpg/sbt-ci-release) to automatically release artifacts from tags.

See https://github.com/NeQuissimus/test-and-stuff for some help with keys and Sonatype.

**Comment by NeQuissimus** [comment]
@manub How have you been deploying artifacts so far?
I have been sucked into a bunch of work before the end of the year and won't have time to set up deployments yet.

**Comment by francescopellegrini** [comment]
I got familiar with keys and Sonatype by working on this tiny library (https://github.com/francescopellegrini/logback-capturing-appender), so maybe I can help managing that part..

**Comment by manub** [comment]
We would need to create a Sonatype account for the org - I've been using bintray and then from there publishing into Maven Central.

**Comment by NeQuissimus** [comment]
@francescopellegrini If you want to do that, you are welcome to. Please make sure that the entire publishing process is automated via Travis.

**Comment by francescopellegrini** [comment]
I'm digging the sbt plugin mentioned here while I wait for the Sonatype account...

**Comment by NeQuissimus** [comment]
Check the README in https://github.com/NeQuissimus/test-and-stuff
It literally has everything you need to know. (because I kept forgetting :D)

**Comment by francescopellegrini** [comment]
@NeQuissimus We've created a group chat in Keybase for you to join. ;)

**Comment by francescopellegrini** [comment]
I opened the issue on Sonatype: https://issues.sonatype.org/browse/OSSRH-44950
