### ISSUE TITLE
Redefine release process

### ISSUE THREAD

**Issue by francescopellegrini** [embeddedkafka/embedded-kafka#20]
Travis pipeline is configured to publish tagged releases automatically.

However, `sbt release` will also publish built artifacts.

I think we need to change the behavior by redefining the release process, in order to be able to run `sbt release` locally just to bump project version:

```scala
releaseProcess := Seq[ReleaseStep](
  setReleaseVersion,
  commitReleaseVersion,
  tagRelease,
  setNextVersion,
  commitNextVersion,
  pushChanges
)
```

**Comment by manub** [comment]
Yes that looks correct to me.
