### ISSUE TITLE
Allow to specify timeout for consumer utility functions

### ISSUE THREAD

**Issue by davideicardi** [embeddedkafka/embedded-kafka#201]
Do you think that we can add a parameter to override timeout for functions like `consumeNumberKeyedMessagesFrom`?

Can I open a PR for that? thanks

**Comment by francescopellegrini** [comment]
Hi @davideicardi,
you can leverage the `consumeNumberKeyedMessagesFromTopics` method, which accepts a timeout parameter.

**Comment by davideicardi** [comment]
Yes I see this function. The problem is that there are a lot of other functions that will not accept timeout, and use a default of 15 sec , that I cannot use.
Maybe we can reorganize these functions so that you can always specify a timeout? Or maybe we can just increase the default timeout?

When working with an intermediate KTable I see that I need at lease 45-60 secs...

**Comment by francescopellegrini** [comment]
When testing aggregations, I usually override the commit interval by providing an extra property to the Streams.

```scala
val extraConf = Map(
  // The commit interval for flushing records to state stores and downstream must be lower than
  // test's timeout (5 secs) to ensure we observe the expected processing results.
  StreamsConfig.COMMIT_INTERVAL_MS_CONFIG -> 3.seconds.toMillis.toString
)
runStreams(topicsToCreate, topology, extraConf) {
  // ...
}
```

I evaluated adding more methods to provide this flexibility, but I'd need to deprecate the existing ones first, or else we'll end up with loads of very similar methods for the same use case.

**Comment by davideicardi** [comment]
You are right, this is a better solution also to improve the test time. Closing issue for now.

Thanks!
