### ISSUE TITLE
Error publishing artifacts to Maven Central?

### ISSUE THREAD

**Issue by francescopellegrini** [embeddedkafka/embedded-kafka#24]
During the first cross-version release [we got an error](https://travis-ci.org/embeddedkafka/embedded-kafka/jobs/471175547), though it seems not to have compromised the artifact publishing.
The error looks very close to [this issue](https://github.com/scalacenter/sbt-release-early/issues/18#issuecomment-336848716).

Investigate on the consequences of the error and how to prevent it.

**Comment by NeQuissimus** [comment]
I do not know of a way to prevent this but we have this in scalaz/scalaz-zio all the time.
That's why you need to do `sbt ci-release || sbt sonatypeReleaseAll`.
