### ISSUE TITLE
Does embedded kafka automatically create topic even if I don't provide the @EmbeddedKafka(topics={"topic-name"},partitions = 3) in my integration test class

### ISSUE THREAD

**Issue by prottoyghose** [embeddedkafka/embedded-kafka#293]
- I have seen a behavior where if I take off @EmbeddedKafka(topics={"topic-name"},partitions = 3) annotation in my integration test class and provide a hardcoded topic-name inside the Kafka Library's send method it still works. Is this the correct behavior that it automatically does that?

**Comment by francescopellegrini** [comment]
Hi @prottoyghose, by default Kafka brokers [allow any producer to create its own topics](https://docs.confluent.io/platform/current/installation/configuration/broker-configs.html#brokerconfigs_auto.create.topics.enable) before writing to them, so yes, this is the expected behavior.
