### ISSUE TITLE
Deserializer custom types

### ISSUE THREAD

**Issue by SarpongAbasimi** [embeddedkafka/embedded-kafka#294]
Hey, If I have this type

```
sealed trait OperationType extends Product with Serializable
 final case object NewSubscription                   extends OperationType
  final case object DeleteSubscription                extends OperationType
  final case class Organization(organization: String) extends AnyVal

  final case class MessageEvent(
      operationType: OperationType,
      organization: Organization,
      repository: Repository
  )
```

I am trying to create a custom `deserializer` for the `MessageEvent` type just like we have for String.
Is there an `Api` for this please?

Ref - https://github.com/embeddedkafka/embedded-kafka/blob/master/embedded-kafka/src/test/scala/io/github/embeddedkafka/EmbeddedKafkaMethodsSpec.scala#L126

No reply so closing this issue but I still would love an answer

**Comment by francescopellegrini** [comment]
Hi @SarpongAbasimi, sorry for the late reply.
You can serialize case classes using Avro, Protobuf, or JSON, all of which are supported by [Confluent Schema Registry](https://docs.confluent.io/platform/current/schema-registry/index.html#avro-json-and-protobuf-supported-formats-and-extensibility).
You can find an example using JSON [here](https://github.com/embeddedkafka/embedded-kafka/tree/master/embedded-kafka/src/test/scala/io/github/embeddedkafka/serializers).
