### ISSUE TITLE
Rename artifacts

### ISSUE THREAD

**Issue by NeQuissimus** [embeddedkafka/embedded-kafka#3]
`"io.github.embeddedkafka" %% "embeddedkafka" % "2.1.0"` ?

**Comment by francescopellegrini** [comment]
Are we going to rename packages as well? It would break BC though...

**Comment by NeQuissimus** [comment]
I was going to leave that for now...
Not sure...

**Comment by martyphee** [comment]
Is the jar available anywhere?  I can't seem to download it.

**Comment by francescopellegrini** [comment]
Aren't we skipping 2.0.1 version here? @manub bumped to 2.1.0-SNAPSHOT directly from 2.0.0 in 93393ec...

**Comment by NeQuissimus** [comment]
I think it is OK to skip 2.0.1. I am running 2.0.0 with 2.0.1 `kafka-clients` transitively pulled in and things are fine.
Let's get all these things right starting with 2.1.0.

**Comment by manub** [comment]
I agree.

Do we want to set up a Slack for this by the way? it may be useful.

**Comment by NeQuissimus** [comment]
Sure, go ahead :)

**Comment by francescopellegrini** [comment]
Shall we close this and continue on #7, where I suggested all 3 new names for the modules, or viceversa?
