### ISSUE TITLE
Cross compile with Scala2.13

### ISSUE THREAD

**Issue by paualarco** [embeddedkafka/embedded-kafka#314]
Hello!

Given that the library is currently only being published for scala 2.12, I wanted to know if there where any intentions to cross compile it with scala 2.13?

**Comment by francescopellegrini** [comment]
Hi @paualarco ,
the library has actually been cross-published [since v2.4.0](https://search.maven.org/artifact/io.github.embeddedkafka/embedded-kafka_2.13/2.4.0/jar).

**Comment by paualarco** [comment]
That's right, sorry I was looking it by the [old artifact groupId](https://mvnrepository.com/artifact/net.manub/scalatest-embedded-kafka), thanks :)
