### ISSUE TITLE
Build with Scala 2.13

### ISSUE THREAD

**Issue by ennru** [embeddedkafka/embedded-kafka#33]
Akka is now published for Scala 2.13.0-M5. 
It would be great to get an *embedded-kafka* version for it.

**Comment by francescopellegrini** [comment]
Waiting for Apache to release a 2.13-compatible version of Kafka...

https://issues.apache.org/jira/browse/KAFKA-7197

**Comment by tayvs** [comment]
@francescopellegrini be aware, https://github.com/apache/kafka/pull/5454

**Comment by francescopellegrini** [comment]
They still have issues when compiling, apparently: apache/kafka#6989

**Comment by tayvs** [comment]
@francescopellegrini https://github.com/apache/kafka/pull/6989 already merged)

**Comment by francescopellegrini** [comment]
> @francescopellegrini [apache/kafka#6989](https://github.com/apache/kafka/pull/6989) already merged)

Probably coming in 2.4.0

**Comment by pvillega** [comment]
Any update on this? Do you have an ETA for 2.4.0? Is there anything needed to push it over the line we can help with?

**Comment by gmarti** [comment]
apache released kafka right ?
Any blockers for 2.13 ?

**Comment by francescopellegrini** [comment]
> apache released kafka right ?
> Any blockers for 2.13 ?

Apache did not release Kafka 2.4.0 yet, unfortunately.

**Comment by seglo** [comment]
I've added 2.13 cross-build in #98

**Comment by francescopellegrini** [comment]
#111 adds Scala 2.13 to the list of versions Travis builds.

**Comment by markusthoemmes** [comment]
Kafka 2.4.0 is released at least as of https://mvnrepository.com/artifact/org.apache.kafka/kafka. Any other blockers here?

**Comment by NeQuissimus** [comment]
Should be good to go

**Comment by francescopellegrini** [comment]
Solved by #111.
