### ISSUE TITLE
New release for Kafka 3.0.1

### ISSUE THREAD

**Issue by andreisilviudragnea** [embeddedkafka/embedded-kafka#352]
When will the new version be released? I cannot find it here for now: https://mvnrepository.com/artifact/io.github.embeddedkafka/embedded-kafka

**Comment by andreisilviudragnea** [comment]
@francescopellegrini

**Comment by francescopellegrini** [comment]
Hi @andreisilviudragnea , I suppose you mean v3.1.0, not v3.0.1, but anyway a new release has not been created yet. It will definitely happen in the next days.
