### ISSUE TITLE
Scala 3 support, pretty please :)

### ISSUE THREAD

**Issue by jozic** [embeddedkafka/embedded-kafka#411]

**Comment by francescopellegrini** [comment]
Hi @jozic, unfortunately I don't have the time anymore to extend this project to support Scala 3. :(

**Comment by francescopellegrini** [comment]
Also, shouldn't we wait for official support (https://github.com/apache/kafka/pull/11350)?

**Comment by mihaisoloi** [comment]
@francescopellegrini it works with cross-compilation from 2.13, it might be years till they decide to support Scala 3 in the official kafka client
