### ISSUE TITLE
embedded-kafka maintenance help

### ISSUE THREAD

**Issue by guizmaii** [embeddedkafka/embedded-kafka#442]
Hi @francescopellegrini @NeQuissimus,

As already explained to Francesco on LinkedIn, I'd like to propose my help in maintaining this project.

I work for [Conduktor](https://www.conduktor.io/), a company making tools on top of Kafka, and I'm one of the maintainers of [zio-kafka](https://github.com/zio/zio-kafka)

embedded-kafka is an important library for both of these projects, that's why I'd like to provide my help to maintain this project.

Is that something you'd be interested in?

Cheers,
Jules 🙂

**Comment by francescopellegrini** [comment]
Hi @guizmaii, while we wait for @NeQuissimus opinion, I'm going to add you as outside collaborator to the embeddedkafka org. :)

**Comment by francescopellegrini** [comment]
Hi @guizmaii , you should now have write access to all repos.
