### ISSUE TITLE
Remove link to original fork

### ISSUE THREAD

**Issue by lukestephenson-zendesk** [embeddedkafka/embedded-kafka#50]
Github doesn't allow searching on repositories which are forked.

![image](https://user-images.githubusercontent.com/48660846/56636348-ce69ed00-66ab-11e9-9ef4-77a6f0760295.png)

Can the link be removed so this repository can be searched.

**Comment by francescopellegrini** [comment]
Hi,
it looks like you have to specify `fork:true` in your search (as mentioned [here](https://github.com/Bajoja/indicator-kdeconnect/issues/152)).

I don't know about detaching from the parent repo.. @manub, what do you think?

**Comment by manub** [comment]
I'm open to what works best for the repo :)

**Comment by francescopellegrini** [comment]
I've just sent the detach request to Github support.

**Comment by francescopellegrini** [comment]
Github support removed the link to the original repo few minutes ago.
