### ISSUE TITLE
v3.7.1 didn't get published

### ISSUE THREAD

**Issue by francescopellegrini** [embeddedkafka/embedded-kafka#509]
Apparently there has been [an error in the CI run](https://github.com/embeddedkafka/embedded-kafka/actions/runs/9770165328/job/26970928807#step:4:220).

I think we need to generate a [user token](https://central.sonatype.org/publish/generate-token/) to solve this

**Comment by francescopellegrini** [comment]
User token has been created

**Comment by francescopellegrini** [comment]
Waiting on the new release of `sbt-ci-release` which will allegedly include https://github.com/sbt/sbt-ci-release/pull/298

**Comment by gaeljw** [comment]
Out of curiosity, why do we need a new release of sbt-ci-release? I know a couple of projects publishing to Sonatype with a token with the current version of sbt-ci-release :thinking: 

In the meantime, it could be helpful for users to add a note in the release note (https://github.com/embeddedkafka/embedded-kafka/releases/tag/v3.7.1) that it's not actually published.

**Comment by francescopellegrini** [comment]
https://github.com/embeddedkafka/embedded-kafka/pull/513 should've fixed this, creating a new release
