### ISSUE TITLE
multiple brokers

### ISSUE THREAD

**Issue by axaluss** [embeddedkafka/embedded-kafka#63]
it's not possible to configure multiple brokers.

**Comment by francescopellegrini** [comment]
Hi @axaluss, it is indeed true that you cannot startup multiple embedded brokers, although I don't fully understand why you would like to do so in a testing scenario..

**Comment by axaluss** [comment]
if your kafka client is also doing changes to topic config and replication or you want to test behavior if brokers enter and exit the cluster, it's nice to have
