### ISSUE TITLE
Misalignment of name for the Schema Registry module

### ISSUE THREAD

**Issue by francescopellegrini** [embeddedkafka/embedded-kafka#7]
In 162c5e1 @NeQuissimus updated the `README.md` setting `embeddedkafka-confluent` as new name for the Schema Registry module, though the value in `build.sbt` was set to `embeddedkafka-schema-registry`.

Which one do you think would be the most correct? I'm afraid of consequences if we decide to mention Confluent...

I'd like to discuss this along with #3.

My suggestions:

- `"io.github.embeddedkafka" %% "embedded-kafka"`
- `"io.github.embeddedkafka" %% "embedded-kafka-streams"`
- `"io.github.embeddedkafka" %% "embedded-kafka-schema-registry"`

**Comment by NeQuissimus** [comment]
Sounds like a plan, I like those names

**Comment by francescopellegrini** [comment]
I pushed again to #10 removing any reference to the `schema-registry` sub-module.
