### ISSUE TITLE
Support for SSL

### ISSUE THREAD

**Issue by politrons** [embeddedkafka/embedded-kafka#78]
Hi, thanks for the great job, the library is really useful. 
One question, do you know if the library has support to run the Kafka embedded in SSL?

Regards

**Comment by francescopellegrini** [comment]
Hi @politrons, thank you very much for your kind words!

I've never tested this use case, but I believe it's already supported: you can provide the required configuration properties to broker, consumers, and producers via [config](https://github.com/embeddedkafka/embedded-kafka/blob/master/embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafkaConfig.scala#L15): see `customBrokerProperties`, `customProducerProperties`, and `customConsumerProperties`.

**Comment by politrons** [comment]
Thanks a lot, we prove that works!
