### ISSUE TITLE
Not sure if the example test is the old one

### ISSUE THREAD

**Issue by ppromsuban** [embeddedkafka/embedded-kafka#82]
Im trying to use `EmbeddedKafkaStreamsAllInOne` from this example https://github.com/embeddedkafka/embedded-kafka/blob/master/kafka-streams/src/test/scala/net/manub/embeddedkafka/streams/ExampleKafkaStreamsSpec.scala

It seems to have been removed. Is there an update to this test. If so i can do pr to modify.

Thanks

**Comment by francescopellegrini** [comment]
Hi @ppromsuban, not sure I understood your question: the test class your linked is working and it's referencing [this library class](https://github.com/embeddedkafka/embedded-kafka/blob/master/kafka-streams/src/main/scala/net/manub/embeddedkafka/streams/EmbeddedKafkaStreamsAllInOne.scala).
Can you explain your issue in more detail, please?

**Comment by ppromsuban** [comment]
Hi @francescopellegrini thanks for replying
Please take a look at the below images
![Screen Shot 2019-10-10 at 3 23 01 PM](https://user-images.githubusercontent.com/12114004/66551566-f1ad2980-eb71-11e9-89f2-4b4d8c57cd29.png)
![Screen Shot 2019-10-10 at 3 22 53 PM](https://user-images.githubusercontent.com/12114004/66551577-f4a81a00-eb71-11e9-89b2-fd2a89822b72.png)
![Screen Shot 2019-10-10 at 3 21 32 PM](https://user-images.githubusercontent.com/12114004/66551585-f7a30a80-eb71-11e9-9a1f-cc82f2690e88.png)

Is it because I am using scala 2.12?

**Comment by francescopellegrini** [comment]
If you need classes from the Streams package you should use the following import instead:
>"io.github.embeddedkafka" %% "embedded-kafka-streams" % "2.3.0" % Test

**Comment by francescopellegrini** [comment]
@ppromsuban can you please confirm if your issue was solved?
